export enum RolUsuario {
  ADMIN = 'ADMIN',
  GESTOR = 'GESTOR',
  CIUDADANO = 'CIUDADANO',
  COORDINADOR = 'COORDINADOR',
  FUNCIONARIO = 'FUNCIONARIO',
  SUPERVISOR = 'SUPERVISOR',
  ATENCION = 'ATENCION'
}
