export enum RolUsuario {
  ADMIN = 'ADMIN',
  USER = 'USER',
  GESTOR = 'GESTOR',
  CIUDADANO = 'CIUDADANO',
  COORDINADOR = 'COORDINADOR',
  FUNCIONARIO = 'FUNCIONARIO',
  SUPERVISOR = 'SUPERVISOR',
  ATENCION_AL_USUARIO = 'ATENCION_AL_USUARIO',
}

